---
#Hosts file that define Vars for Individual hosts. Use Groups file if one VAR can be applied to mulitple units

dist-sw01:
    hostname: "10.10.20.177"
    groups: 
        - us_east
dist-sw02:
    hostname: "10.10.20.178"
    groups: 
        - us_west
